# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6e76bcea016c7b8ee50cb5a88facfcd229f8020065f745376475aad0e7dbb7c5fa4631d5b47c2fc7a5529702877ba0b1d9a3deed9fd07869439b04578508ea06

test:
  secret_key_base: df9da86ebcfdf9018285095ec9d69f028466e8c0c2aa0becbe16f015183aa271ebd2fb73b978d640bba3b844da452dc01ca548ca54da20c0edd2a25e37519233

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
